#!/bin/bash
PERSON1=vicky    
PERSON2=Ram

 echo "$PERSON1: hi $PERSON2"
 echo "$PERSON2: hello $PERSON1"
 echo "$PERSON1: how are you $PERSON2"
 echo "$PERSON2: fine what about you $PERSON1"
 echo "$PERSON1: i'm fine about you $PERSON2"